/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bouncingballsV2;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AKN
 */
public class frmMain extends javax.swing.JFrame implements Runnable {

    private Thread t;
    private ArrayList<Ball> balls;
    
    private Ball currentEllipse;
    private int ballCount=2;
    private boolean isPaused=true;
  
 

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        t = new Thread(this);
        balls = new ArrayList<Ball>();

        Ball ball1 = new Ball();
        ball1.setColor(Color.GREEN);
        ball1.setName("Ball1");
        ball1.setX(20);
        ball1.setY(drawPanel.getHeight() - 80);
        ball1.setAngle(0);
        ball1.setRadius(30);
        ball1.setSpeedMultiplier(0.01);
        ball1.setDx(0.01);
        ball1.setDy(0.01);
        
       
    
        balls.add(ball1);
        
        Ball ball2 = new Ball();
        ball2.setColor(Color.BLUE);
        ball2.setName("Ball2");
        ball2.setX(drawPanel.getWidth() - 80);
        ball2.setY(drawPanel.getHeight() - 80);
        ball2.setAngle(0);
        ball2.setRadius(30);
        ball2.setSpeedMultiplier(0.01);
        ball2.setDx(0.01);
        ball2.setDy(0.01);
        
        
        balls.add(ball2);
        
        GameStateAndAction.initialize();
        GameStateAndAction.setBalls(balls);
        GameStateAndAction.setPanel(drawPanel);
        GameStateAndAction.setFrame(this);
        GameStateAndAction.setEndSignal(true);
        
      
        
        GameStateAndAction.setSliderAngle1(sliderAngle1.getValue());
        GameStateAndAction.setSliderAngle2(sliderAngle2.getValue());
        GameStateAndAction.setSliderAngle3(sliderAngle3.getValue());
        GameStateAndAction.setSliderAngle4(sliderAngle4.getValue());
        GameStateAndAction.setSliderAngle5(sliderAngle5.getValue());
        
        GameStateAndAction.setSliderMass1(sliderMass1.getValue());
        GameStateAndAction.setSliderMass2(sliderMass2.getValue());
        GameStateAndAction.setSliderMass3(sliderMass3.getValue());
        GameStateAndAction.setSliderMass4(sliderMass4.getValue());
        GameStateAndAction.setSliderMass5(sliderMass5.getValue());
        
        GameStateAndAction.setSliderRadius1(sliderRadius1.getValue());
        GameStateAndAction.setSliderRadius2(sliderRadius2.getValue());
        GameStateAndAction.setSliderRadius3(sliderRadius3.getValue());
        GameStateAndAction.setSliderRadius4(sliderRadius4.getValue());
        GameStateAndAction.setSliderRadius5(sliderRadius5.getValue());
        
        GameStateAndAction.setSpeed1(Float.parseFloat(txtSpeed1.getText()));
        GameStateAndAction.setSpeed2(Float.parseFloat(txtSpeed2.getText()));
        GameStateAndAction.setSpeed3(Float.parseFloat(txtSpeed3.getText()));
        GameStateAndAction.setSpeed4(Float.parseFloat(txtSpeed4.getText()));
        GameStateAndAction.setSpeed5(Float.parseFloat(txtSpeed5.getText()));
        
        
        jTabbedPane1.removeTabAt(4);
        jTabbedPane1.removeTabAt(3);
        jTabbedPane1.removeTabAt(2);
        
        jLabelBall3VelX.setVisible(false);
        jLabelBall3VelY.setVisible(false);
        jLabelBall4VelX.setVisible(false);
        jLabelBall4VelY.setVisible(false);
        jLabelBall5VelX.setVisible(false);
        jLabelBall5VelY.setVisible(false);
        
        jTextFieldBall3VelX.setVisible(false);
        jTextFieldBall3VelY.setVisible(false);
        jTextFieldBall4VelX.setVisible(false);
        jTextFieldBall4VelY.setVisible(false);
        jTextFieldBall5VelX.setVisible(false);
        jTextFieldBall5VelY.setVisible(false);
        
        
        this.setLocationRelativeTo(null);

    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGroupCollision = new javax.swing.ButtonGroup();
        btnReset = new javax.swing.JButton();
        drawPanel = new javax.swing.JPanel(){
            @Override
            public void paint(Graphics g) {
                super.paintComponent(g);
                Graphics2D g1 = (Graphics2D) g;
                for (Ball ball : balls) {

                    g1.setColor(ball.getColor());
                    g1.fill(ball.getShape());
                    g1.draw(ball.getShape());
                    ball.move(this.getBounds());
                    //GameStateAndAction.checkAndHandleCollision(ball);

                }

            }
        };
        btnStartPause = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtSpeed1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sliderAngle1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sliderMass1 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        sliderRadius1 = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        txtSpeed2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sliderAngle2 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sliderMass2 = new javax.swing.JSlider();
        sliderRadius2 = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtSpeed3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sliderAngle3 = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sliderMass3 = new javax.swing.JSlider();
        sliderRadius3 = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtSpeed4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sliderAngle4 = new javax.swing.JSlider();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sliderMass4 = new javax.swing.JSlider();
        sliderRadius4 = new javax.swing.JSlider();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtSpeed5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        sliderAngle5 = new javax.swing.JSlider();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        sliderMass5 = new javax.swing.JSlider();
        sliderRadius5 = new javax.swing.JSlider();
        jLabel24 = new javax.swing.JLabel();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jRadioButtonElastic = new javax.swing.JRadioButton();
        jRadioButtonInelastic = new javax.swing.JRadioButton();
        jButtonAddBall = new javax.swing.JButton();
        jButtonRemoveBall = new javax.swing.JButton();
        jPanelBallVelocity = new javax.swing.JPanel();
        jLabelBall1VelX = new javax.swing.JLabel();
        jLabelBall1VelY = new javax.swing.JLabel();
        jLabelBall2VelX = new javax.swing.JLabel();
        jLabelBall2VelY = new javax.swing.JLabel();
        jTextFieldBall1VelX = new javax.swing.JTextField();
        jTextFieldBall1VelY = new javax.swing.JTextField();
        jTextFieldBall2VelX = new javax.swing.JTextField();
        jTextFieldBall2VelY = new javax.swing.JTextField();
        jLabelBall3VelX = new javax.swing.JLabel();
        jTextFieldBall3VelX = new javax.swing.JTextField();
        jLabelBall3VelY = new javax.swing.JLabel();
        jLabelBall4VelY = new javax.swing.JLabel();
        jTextFieldBall3VelY = new javax.swing.JTextField();
        jTextFieldBall4VelY = new javax.swing.JTextField();
        jLabelBall4VelX = new javax.swing.JLabel();
        jTextFieldBall4VelX = new javax.swing.JTextField();
        jLabelBall5VelX = new javax.swing.JLabel();
        jTextFieldBall5VelX = new javax.swing.JTextField();
        jLabelBall5VelY = new javax.swing.JLabel();
        jTextFieldBall5VelY = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bouncing Balls");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnReset.setText("Re-Set");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        drawPanel.setBackground(new java.awt.Color(255, 255, 255));
        drawPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drawPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drawPanelMousePressed(evt);
            }
        });
        drawPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                drawPanelMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drawPanelMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        btnStartPause.setText("Start/Pause");
        btnStartPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartPauseActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Object -I Settings"));
        jPanel1.setToolTipText("");

        txtSpeed1.setText("0.01");
        txtSpeed1.setToolTipText("");
        txtSpeed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpeed1ActionPerformed(evt);
            }
        });
        txtSpeed1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtSpeed1InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtSpeed1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSpeed1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSpeed1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSpeed1KeyTyped(evt);
            }
        });

        jLabel1.setText("Set Angle(Degrees):");

        sliderAngle1.setMajorTickSpacing(10);
        sliderAngle1.setMaximum(90);
        sliderAngle1.setMinorTickSpacing(5);
        sliderAngle1.setPaintLabels(true);
        sliderAngle1.setPaintTicks(true);
        sliderAngle1.setToolTipText("");
        sliderAngle1.setValue(0);
        sliderAngle1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAngle1StateChanged(evt);
            }
        });

        jLabel2.setText("<html>Movement Speed Multiplier<br/>(0.0 to 5.0)");

        jLabel6.setText("Mass:");

        sliderMass1.setMajorTickSpacing(1);
        sliderMass1.setMaximum(10);
        sliderMass1.setMinimum(1);
        sliderMass1.setMinorTickSpacing(1);
        sliderMass1.setPaintLabels(true);
        sliderMass1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMass1StateChanged(evt);
            }
        });

        jLabel7.setText("Radius:");

        sliderRadius1.setMajorTickSpacing(10);
        sliderRadius1.setMaximum(70);
        sliderRadius1.setMinimum(10);
        sliderRadius1.setMinorTickSpacing(5);
        sliderRadius1.setPaintLabels(true);
        sliderRadius1.setToolTipText("");
        sliderRadius1.setValue(30);
        sliderRadius1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRadius1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                            .addComponent(sliderRadius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sliderMass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtSpeed1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(sliderAngle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderAngle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSpeed1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sliderMass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sliderRadius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        jTabbedPane1.addTab("Object 1", jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("Object -1 Settings");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Object -II Settings"));

        txtSpeed2.setText("0.01");
        txtSpeed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpeed2ActionPerformed(evt);
            }
        });
        txtSpeed2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtSpeed2InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtSpeed2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSpeed2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSpeed2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSpeed2KeyTyped(evt);
            }
        });

        jLabel3.setText("Set Angle(Degrees):");

        sliderAngle2.setMajorTickSpacing(10);
        sliderAngle2.setMaximum(90);
        sliderAngle2.setMinorTickSpacing(5);
        sliderAngle2.setPaintLabels(true);
        sliderAngle2.setPaintTicks(true);
        sliderAngle2.setToolTipText("");
        sliderAngle2.setValue(0);
        sliderAngle2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAngle2StateChanged(evt);
            }
        });

        jLabel4.setText("<html>Movement Speed Multiplier<br/>(0.0 to 5.0)");

        jLabel5.setText("Mass:");

        sliderMass2.setMajorTickSpacing(1);
        sliderMass2.setMaximum(10);
        sliderMass2.setMinimum(1);
        sliderMass2.setMinorTickSpacing(1);
        sliderMass2.setPaintLabels(true);
        sliderMass2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMass2StateChanged(evt);
            }
        });

        sliderRadius2.setMajorTickSpacing(10);
        sliderRadius2.setMaximum(70);
        sliderRadius2.setMinimum(10);
        sliderRadius2.setMinorTickSpacing(5);
        sliderRadius2.setPaintLabels(true);
        sliderRadius2.setToolTipText("");
        sliderRadius2.setValue(30);
        sliderRadius2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRadius2StateChanged(evt);
            }
        });

        jLabel8.setText("Radius:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderRadius2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSpeed2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sliderAngle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderMass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(sliderAngle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSpeed2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(sliderMass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(sliderRadius2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3)
                    .addContainerGap(177, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Object II", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Object -III Settings"));

        txtSpeed3.setText("0.01");
        txtSpeed3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpeed3ActionPerformed(evt);
            }
        });
        txtSpeed3.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtSpeed3InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtSpeed3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSpeed3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSpeed3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSpeed3KeyTyped(evt);
            }
        });

        jLabel9.setText("Set Angle(Degrees):");

        sliderAngle3.setMajorTickSpacing(10);
        sliderAngle3.setMaximum(90);
        sliderAngle3.setMinorTickSpacing(5);
        sliderAngle3.setPaintLabels(true);
        sliderAngle3.setPaintTicks(true);
        sliderAngle3.setValue(45);
        sliderAngle3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAngle3StateChanged(evt);
            }
        });

        jLabel10.setText("<html>Movement Speed Multiplier<br/>(0.0 to 5.0)");

        jLabel11.setText("Mass:");

        sliderMass3.setMajorTickSpacing(1);
        sliderMass3.setMaximum(10);
        sliderMass3.setMinimum(1);
        sliderMass3.setMinorTickSpacing(1);
        sliderMass3.setPaintLabels(true);
        sliderMass3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMass3StateChanged(evt);
            }
        });

        sliderRadius3.setMajorTickSpacing(10);
        sliderRadius3.setMaximum(70);
        sliderRadius3.setMinimum(10);
        sliderRadius3.setMinorTickSpacing(5);
        sliderRadius3.setPaintLabels(true);
        sliderRadius3.setToolTipText("");
        sliderRadius3.setValue(30);
        sliderRadius3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRadius3StateChanged(evt);
            }
        });

        jLabel12.setText("Radius:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderRadius3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sliderAngle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderMass3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSpeed3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(sliderAngle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSpeed3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(sliderMass3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(sliderRadius3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9)
                    .addContainerGap(177, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Object III", null, jPanel3, "");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Object -IV Settings"));

        txtSpeed4.setText("0.01");
        txtSpeed4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpeed4ActionPerformed(evt);
            }
        });
        txtSpeed4.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtSpeed4InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtSpeed4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSpeed4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSpeed4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSpeed4KeyTyped(evt);
            }
        });

        jLabel13.setText("Set Angle(Degrees):");

        sliderAngle4.setMajorTickSpacing(10);
        sliderAngle4.setMaximum(90);
        sliderAngle4.setMinorTickSpacing(5);
        sliderAngle4.setPaintLabels(true);
        sliderAngle4.setPaintTicks(true);
        sliderAngle4.setValue(45);
        sliderAngle4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAngle4StateChanged(evt);
            }
        });

        jLabel14.setText("<html>Movement Speed Multiplier<br/>(0.0 to 5.0)");

        jLabel15.setText("Mass:");

        sliderMass4.setMajorTickSpacing(1);
        sliderMass4.setMaximum(10);
        sliderMass4.setMinimum(1);
        sliderMass4.setMinorTickSpacing(1);
        sliderMass4.setPaintLabels(true);
        sliderMass4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMass4StateChanged(evt);
            }
        });

        sliderRadius4.setMajorTickSpacing(10);
        sliderRadius4.setMaximum(70);
        sliderRadius4.setMinimum(10);
        sliderRadius4.setMinorTickSpacing(5);
        sliderRadius4.setPaintLabels(true);
        sliderRadius4.setToolTipText("");
        sliderRadius4.setValue(30);
        sliderRadius4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRadius4StateChanged(evt);
            }
        });

        jLabel16.setText("Radius:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderRadius4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sliderAngle4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderMass4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSpeed4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(sliderAngle4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSpeed4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(sliderMass4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(sliderRadius4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13)
                    .addContainerGap(177, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Object IV", null, jPanel4, "");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Object -V Settings"));

        txtSpeed5.setText("0.01");
        txtSpeed5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpeed5ActionPerformed(evt);
            }
        });
        txtSpeed5.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtSpeed5InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtSpeed5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSpeed5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSpeed5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSpeed5KeyTyped(evt);
            }
        });

        jLabel21.setText("Set Angle(Degrees):");

        sliderAngle5.setMajorTickSpacing(10);
        sliderAngle5.setMaximum(90);
        sliderAngle5.setMinorTickSpacing(5);
        sliderAngle5.setPaintLabels(true);
        sliderAngle5.setPaintTicks(true);
        sliderAngle5.setValue(45);
        sliderAngle5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAngle5StateChanged(evt);
            }
        });

        jLabel22.setText("<html>Movement Speed Multiplier<br/>(0.0 to 5.0)");

        jLabel23.setText("Mass:");

        sliderMass5.setMajorTickSpacing(1);
        sliderMass5.setMaximum(10);
        sliderMass5.setMinimum(1);
        sliderMass5.setMinorTickSpacing(1);
        sliderMass5.setPaintLabels(true);
        sliderMass5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMass5StateChanged(evt);
            }
        });

        sliderRadius5.setMajorTickSpacing(10);
        sliderRadius5.setMaximum(70);
        sliderRadius5.setMinimum(10);
        sliderRadius5.setMinorTickSpacing(5);
        sliderRadius5.setPaintLabels(true);
        sliderRadius5.setToolTipText("");
        sliderRadius5.setValue(30);
        sliderRadius5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRadius5StateChanged(evt);
            }
        });

        jLabel24.setText("Radius:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderRadius5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sliderAngle5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderMass5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSpeed5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel21)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(sliderAngle5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSpeed5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(sliderMass5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(sliderRadius5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel21)
                    .addContainerGap(177, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Object V", null, jPanel5, "");

        jButtonGroupCollision.add(jRadioButtonNo);
        jRadioButtonNo.setSelected(true);
        jRadioButtonNo.setText("No Collision");
        jRadioButtonNo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonNoStateChanged(evt);
            }
        });

        jButtonGroupCollision.add(jRadioButtonElastic);
        jRadioButtonElastic.setText("Elastic");
        jRadioButtonElastic.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonElasticStateChanged(evt);
            }
        });

        jButtonGroupCollision.add(jRadioButtonInelastic);
        jRadioButtonInelastic.setText("Inelastic");
        jRadioButtonInelastic.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonInelasticStateChanged(evt);
            }
        });

        jButtonAddBall.setText("Add Ball");
        jButtonAddBall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBallActionPerformed(evt);
            }
        });

        jButtonRemoveBall.setText("Remove Ball");
        jButtonRemoveBall.setEnabled(false);
        jButtonRemoveBall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveBallActionPerformed(evt);
            }
        });

        jPanelBallVelocity.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBallVelocity.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ball Final Velocity After Collision", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 1, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabelBall1VelX.setText("Ball 1-X Velocity:");

        jLabelBall1VelY.setText("Ball 1-Y Velocity:");

        jLabelBall2VelX.setText("Ball 2-X Velocity:");

        jLabelBall2VelY.setText("Ball 2-Y Velocity:");

        jTextFieldBall1VelX.setText("0.01");
        jTextFieldBall1VelX.setEnabled(false);

        jTextFieldBall1VelY.setText("0.01");
        jTextFieldBall1VelY.setEnabled(false);

        jTextFieldBall2VelX.setText("0.01");
        jTextFieldBall2VelX.setEnabled(false);

        jTextFieldBall2VelY.setText("0.01");
        jTextFieldBall2VelY.setEnabled(false);

        jLabelBall3VelX.setText("Ball 3-X Velocity:");

        jTextFieldBall3VelX.setText("0.01");
        jTextFieldBall3VelX.setEnabled(false);

        jLabelBall3VelY.setText("Ball 3-Y Velocity:");

        jLabelBall4VelY.setText("Ball 4-Y Velocity:");

        jTextFieldBall3VelY.setText("0.01");
        jTextFieldBall3VelY.setEnabled(false);

        jTextFieldBall4VelY.setText("0.01");
        jTextFieldBall4VelY.setEnabled(false);

        jLabelBall4VelX.setText("Ball 4-X Velocity:");

        jTextFieldBall4VelX.setText("0.01");
        jTextFieldBall4VelX.setEnabled(false);

        jLabelBall5VelX.setText("Ball 5-X Velocity:");

        jTextFieldBall5VelX.setText("0.01");
        jTextFieldBall5VelX.setEnabled(false);

        jLabelBall5VelY.setText("Ball 5-Y Velocity:");

        jTextFieldBall5VelY.setText("0.01");
        jTextFieldBall5VelY.setEnabled(false);

        javax.swing.GroupLayout jPanelBallVelocityLayout = new javax.swing.GroupLayout(jPanelBallVelocity);
        jPanelBallVelocity.setLayout(jPanelBallVelocityLayout);
        jPanelBallVelocityLayout.setHorizontalGroup(
            jPanelBallVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBallVelocityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBallVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBallVelocityLayout.createSequentialGroup()
                        .addGroup(jPanelBallVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBallVelocityLayout.createSequentialGroup()
                                .addComponent(jLabelBall2VelX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBall2VelX))
                            .addGroup(jPanelBallVelocityLayout.createSequentialGroup()
                                .addComponent(jLabelBall1VelX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBall1VelX, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBallVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBallVelocityLayout.createSequentialGroup()
                                .addComponent(jLabelBall2VelY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBall2VelY, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBallVelocityLayout.createSequentialGroup()
                                .addComponent(jLabelBall1VelY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBall1VelY, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelBallVelocityLayout.createSequentialGroup()
                        .addGroup(jPanelBallVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBallVelocityLayout.createSequentialGroup()
                                .addComponent(jLabelBall4VelX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBall4VelX, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBallVelocityLayout.createSequentialGroup()
                                .addComponent(jLabelBall3VelX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBall3VelX, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBallVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBallVelocityLayout.createSequentialGroup()
                                .addComponent(jLabelBall4VelY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBall4VelY, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBallVelocityLayout.createSequentialGroup()
                                .addComponent(jLabelBall3VelY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBall3VelY, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelBallVelocityLayout.createSequentialGroup()
                        .addComponent(jLabelBall5VelX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBall5VelX, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBall5VelY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBall5VelY, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelBallVelocityLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldBall1VelX, jTextFieldBall1VelY, jTextFieldBall2VelX, jTextFieldBall2VelY, jTextFieldBall3VelX, jTextFieldBall3VelY, jTextFieldBall4VelX, jTextFieldBall4VelY, jTextFieldBall5VelX, jTextFieldBall5VelY});

        jPanelBallVelocityLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelBall1VelX, jLabelBall1VelY, jLabelBall2VelX, jLabelBall2VelY, jLabelBall3VelX, jLabelBall3VelY, jLabelBall4VelX, jLabelBall4VelY, jLabelBall5VelX, jLabelBall5VelY});

        jPanelBallVelocityLayout.setVerticalGroup(
            jPanelBallVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBallVelocityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBallVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBall1VelX)
                    .addComponent(jLabelBall1VelY)
                    .addComponent(jTextFieldBall1VelX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBall1VelY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBallVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBall2VelX)
                    .addComponent(jLabelBall2VelY)
                    .addComponent(jTextFieldBall2VelX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBall2VelY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBallVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBall3VelX)
                    .addComponent(jLabelBall3VelY)
                    .addComponent(jTextFieldBall3VelX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBall3VelY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBallVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBall4VelX)
                    .addComponent(jLabelBall4VelY)
                    .addComponent(jTextFieldBall4VelY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBall4VelX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBallVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBall5VelX)
                    .addComponent(jLabelBall5VelY)
                    .addComponent(jTextFieldBall5VelY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBall5VelX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBallVelocityLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldBall1VelX, jTextFieldBall1VelY, jTextFieldBall2VelX, jTextFieldBall2VelY, jTextFieldBall3VelX, jTextFieldBall3VelY, jTextFieldBall4VelX, jTextFieldBall4VelY, jTextFieldBall5VelX, jTextFieldBall5VelY});

        jPanelBallVelocityLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelBall1VelX, jLabelBall1VelY, jLabelBall2VelX, jLabelBall2VelY, jLabelBall3VelX, jLabelBall3VelY, jLabelBall4VelX, jLabelBall4VelY, jLabelBall5VelX, jLabelBall5VelY});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonInelastic)
                    .addComponent(jRadioButtonNo)
                    .addComponent(jRadioButtonElastic)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStartPause, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jButtonAddBall)
                    .addComponent(jButtonRemoveBall))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanelBallVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addComponent(drawPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioButtonElastic, jRadioButtonInelastic, jRadioButtonNo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnReset, btnStartPause, jButtonAddBall, jButtonRemoveBall});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelBallVelocity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStartPause)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddBall)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRemoveBall)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonNo, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonElastic, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonInelastic, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addGap(5, 5, 5)))
                        .addGap(37, 37, 37)))
                .addComponent(drawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnStartPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartPauseActionPerformed
        isPaused = !isPaused;
        
        if(GameStateAndAction.isEndSignal()==true){
            
            t = new Thread(this);
            try {
                t.start();
            } catch (Exception ex) {
            }
        }
        GameStateAndAction.setEndSignal(!GameStateAndAction.isEndSignal());
        
    }//GEN-LAST:event_btnStartPauseActionPerformed

    private void sliderAngle1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAngle1StateChanged
        GameStateAndAction.setSliderAngle1(sliderAngle1.getValue());
    }//GEN-LAST:event_sliderAngle1StateChanged

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

        /* Create and display the form */
        GameStateAndAction.setEndSignal(true);
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnResetActionPerformed

    private void sliderAngle2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAngle2StateChanged
        GameStateAndAction.setSliderAngle2(sliderAngle2.getValue());
    }//GEN-LAST:event_sliderAngle2StateChanged

    private void txtSpeed1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed1KeyTyped

    }//GEN-LAST:event_txtSpeed1KeyTyped

    private void txtSpeed1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtSpeed1InputMethodTextChanged

    }//GEN-LAST:event_txtSpeed1InputMethodTextChanged

    private void txtSpeed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpeed1ActionPerformed

    }//GEN-LAST:event_txtSpeed1ActionPerformed

    private void txtSpeed2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed2KeyTyped


    }//GEN-LAST:event_txtSpeed2KeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            // TODO add your handling code here:
            GameStateAndAction.getWriter().close();

        } catch (IOException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowClosed

    private void txtSpeed2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtSpeed2InputMethodTextChanged

    }//GEN-LAST:event_txtSpeed2InputMethodTextChanged

    private void txtSpeed1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed1KeyReleased
      
        try {
            if (!txtSpeed1.getText().equals("")) {

                if (Float.parseFloat(txtSpeed1.getText()) > 5f) {
                    JOptionPane.showMessageDialog(this, "Please enter value between 0.0 and 5.0.", "Message", JOptionPane.INFORMATION_MESSAGE);
                    txtSpeed1.setText("0.01");

                } else {
                    GameStateAndAction.setIsSpeedChanged1(true);
                    GameStateAndAction.setSpeed1(Float.parseFloat(txtSpeed1.getText()));
                }
            }
        } catch (Exception ex) {
            txtSpeed1.setText("0.01");
        }

    }//GEN-LAST:event_txtSpeed1KeyReleased

    private void txtSpeed2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed2KeyReleased

        try {
            if (!txtSpeed2.getText().equals("")) {
                if (Float.parseFloat(txtSpeed2.getText()) > 5) {
                    JOptionPane.showMessageDialog(this, "Please enter value between 00 and 5.0.", "Message", JOptionPane.INFORMATION_MESSAGE);

                    txtSpeed2.setText("0.01");
                } else {
                    GameStateAndAction.setIsSpeedChanged2(true);
                    GameStateAndAction.setSpeed2(Float.parseFloat(txtSpeed2.getText()));
                }
            }
        } catch (Exception ex) {
            txtSpeed2.setText("0.01");
        }
    }//GEN-LAST:event_txtSpeed2KeyReleased

    private void txtSpeed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpeed2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeed2ActionPerformed

    private void txtSpeed2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed2KeyPressed

    }//GEN-LAST:event_txtSpeed2KeyPressed

    private void txtSpeed1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed1KeyPressed

    }//GEN-LAST:event_txtSpeed1KeyPressed

    private void sliderMass1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMass1StateChanged
        GameStateAndAction.setSliderMass1(sliderMass1.getValue());
    }//GEN-LAST:event_sliderMass1StateChanged

    private void sliderRadius1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRadius1StateChanged
        GameStateAndAction.setSliderRadius1(sliderRadius1.getValue());
    }//GEN-LAST:event_sliderRadius1StateChanged

    private void sliderMass2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMass2StateChanged
        GameStateAndAction.setSliderMass2(sliderMass2.getValue());
    }//GEN-LAST:event_sliderMass2StateChanged

    private void sliderRadius2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRadius2StateChanged
        GameStateAndAction.setSliderRadius2(sliderRadius2.getValue());
        
        
    }//GEN-LAST:event_sliderRadius2StateChanged

    private void txtSpeed3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpeed3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeed3ActionPerformed

    private void txtSpeed3InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtSpeed3InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeed3InputMethodTextChanged

    private void txtSpeed3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeed3KeyPressed

    private void txtSpeed3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed3KeyReleased
        try {
            if (!txtSpeed3.getText().equals("")) {
                if (Float.parseFloat(txtSpeed3.getText()) > 5) {
                    JOptionPane.showMessageDialog(this, "Please enter value between 00 and 5.0.", "Message", JOptionPane.INFORMATION_MESSAGE);

                    txtSpeed3.setText("0.01");
                } else {
                    GameStateAndAction.setIsSpeedChanged3(true);
                    GameStateAndAction.setSpeed3(Float.parseFloat(txtSpeed3.getText()));
                }
            }
        } catch (Exception ex) {
            txtSpeed3.setText("0.01");
        }
    }//GEN-LAST:event_txtSpeed3KeyReleased

    private void txtSpeed3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeed3KeyTyped

    private void sliderAngle3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAngle3StateChanged
        GameStateAndAction.setSliderAngle3(sliderAngle3.getValue());
    }//GEN-LAST:event_sliderAngle3StateChanged

    private void sliderMass3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMass3StateChanged
         GameStateAndAction.setSliderMass3(sliderMass3.getValue());
    }//GEN-LAST:event_sliderMass3StateChanged

    private void sliderRadius3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRadius3StateChanged
         GameStateAndAction.setSliderRadius3(sliderRadius3.getValue());
    }//GEN-LAST:event_sliderRadius3StateChanged

    private void txtSpeed4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpeed4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeed4ActionPerformed

    private void txtSpeed4InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtSpeed4InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeed4InputMethodTextChanged

    private void txtSpeed4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeed4KeyPressed

    private void txtSpeed4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed4KeyReleased
         try {
            if (!txtSpeed4.getText().equals("")) {
                if (Float.parseFloat(txtSpeed4.getText()) > 5) {
                    JOptionPane.showMessageDialog(this, "Please enter value between 00 and 5.0.", "Message", JOptionPane.INFORMATION_MESSAGE);

                    txtSpeed4.setText("0.01");
                } else {
                    GameStateAndAction.setIsSpeedChanged4(true);
                    GameStateAndAction.setSpeed4(Float.parseFloat(txtSpeed4.getText()));
                }
            }
        } catch (Exception ex) {
            txtSpeed4.setText("0.01");
        }
    }//GEN-LAST:event_txtSpeed4KeyReleased

    private void txtSpeed4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeed4KeyTyped

    private void sliderAngle4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAngle4StateChanged
        GameStateAndAction.setSliderAngle4(sliderAngle4.getValue());
    }//GEN-LAST:event_sliderAngle4StateChanged

    private void sliderMass4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMass4StateChanged
         GameStateAndAction.setSliderMass4(sliderMass4.getValue());
    }//GEN-LAST:event_sliderMass4StateChanged

    private void sliderRadius4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRadius4StateChanged
        GameStateAndAction.setSliderRadius4(sliderRadius4.getValue());
    }//GEN-LAST:event_sliderRadius4StateChanged

    private void txtSpeed5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpeed5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeed5ActionPerformed

    private void txtSpeed5InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtSpeed5InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeed5InputMethodTextChanged

    private void txtSpeed5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeed5KeyPressed

    private void txtSpeed5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed5KeyReleased
        try {
            if (!txtSpeed5.getText().equals("")) {
                if (Float.parseFloat(txtSpeed5.getText()) > 5) {
                    JOptionPane.showMessageDialog(this, "Please enter value between 00 and 5.0.", "Message", JOptionPane.INFORMATION_MESSAGE);

                    txtSpeed5.setText("0.01");
                } else {
                    GameStateAndAction.setIsSpeedChanged5(true);
                    GameStateAndAction.setSpeed5(Float.parseFloat(txtSpeed5.getText()));
                }
            }
        } catch (Exception ex) {
            txtSpeed5.setText("0.01");
        }
    }//GEN-LAST:event_txtSpeed5KeyReleased

    private void txtSpeed5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpeed5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeed5KeyTyped

    private void sliderAngle5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAngle5StateChanged
        GameStateAndAction.setSliderAngle5(sliderAngle5.getValue());
    }//GEN-LAST:event_sliderAngle5StateChanged

    private void sliderMass5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMass5StateChanged
         GameStateAndAction.setSliderMass5(sliderMass5.getValue());
    }//GEN-LAST:event_sliderMass5StateChanged

    private void sliderRadius5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRadius5StateChanged
         GameStateAndAction.setSliderRadius5(sliderRadius5.getValue());
    }//GEN-LAST:event_sliderRadius5StateChanged

    private void jRadioButtonNoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonNoStateChanged
        if(jRadioButtonNo.isSelected()==true){
            GameStateAndAction.setCollisionType("none");
        }
        
    }//GEN-LAST:event_jRadioButtonNoStateChanged

    private void jRadioButtonElasticStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonElasticStateChanged
        if(jRadioButtonElastic.isSelected()==true){
            GameStateAndAction.setCollisionType("elastic");
        }
    }//GEN-LAST:event_jRadioButtonElasticStateChanged

    private void jRadioButtonInelasticStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonInelasticStateChanged
        if(jRadioButtonInelastic.isSelected()==true){
            GameStateAndAction.setCollisionType("inelastic");
        }
    }//GEN-LAST:event_jRadioButtonInelasticStateChanged

    private void jButtonAddBallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBallActionPerformed
        
        addBall();
    }//GEN-LAST:event_jButtonAddBallActionPerformed
    private void addBall(){
      if(GameStateAndAction.isEndSignal()==false);{
                GameStateAndAction.setEndSignal(true);
       }
        
       
        //GameStateAndAction.setEndSignal(!GameStateAndAction.isEndSignal());
        
        Ball ball = new Ball();
        int count =  jTabbedPane1.getTabCount();
        String title="";
        JPanel panel=null;
        
        if(count==4){
            jButtonAddBall.setEnabled(false);
            title="Object V";
            panel=jPanel5;
            ball.setColor(Color.PINK);
            ball.setName("Ball5");
            ball.setX(drawPanel.getWidth()/2);
            ball.setY(drawPanel.getHeight()/2);
            ball.setAngle(45);
            ball.setRadius(30);
            ball.setSpeedMultiplier(0.01);
            ball.setDx(0.01);
            ball.setDy(0.01);
            jLabelBall5VelX.setVisible(true);
            jLabelBall5VelY.setVisible(true);
            jTextFieldBall5VelX.setVisible(true);
            jTextFieldBall5VelY.setVisible(true);
 
        }else{
            jButtonAddBall.setEnabled(true);
            
            if(count==2){
                title="Object III";
                panel=jPanel3;
                jButtonRemoveBall.setEnabled(true);
                 ball.setColor(Color.ORANGE);
                ball.setName("Ball3");
                ball.setX(80);
                ball.setY(80);
                ball.setAngle(45);
                ball.setRadius(30);
                ball.setSpeedMultiplier(0.01);
                ball.setDx(0.01);
                ball.setDy(0.01);
                jLabelBall3VelX.setVisible(true);
                jLabelBall3VelY.setVisible(true);
                jTextFieldBall3VelX.setVisible(true);
                jTextFieldBall3VelY.setVisible(true);
            }else if (count==3){
                title="Object IV";
                panel=jPanel4;
                ball.setColor(Color.RED);
                ball.setName("Ball4");
                ball.setX(drawPanel.getWidth() - 80);
                ball.setY(80);
                ball.setAngle(45);
                ball.setRadius(30);
                ball.setSpeedMultiplier(0.01);
                ball.setDx(0.01);
                ball.setDy(0.01);
                jLabelBall4VelX.setVisible(true);
                jLabelBall4VelY.setVisible(true);
                jTextFieldBall4VelX.setVisible(true);
                jTextFieldBall4VelY.setVisible(true);
                }
        }
       jTabbedPane1.addTab(title,panel);
       balls.add(ball);
       GameStateAndAction.setBalls(balls);
      
       if(GameStateAndAction.isEndSignal()==true && isPaused==false){
           GameStateAndAction.setEndSignal(false);
            t = new Thread(this);
            try {
                t.start();
            } catch (Exception ex) {
            }
           
        } 
        
        drawPanel.repaint();
        drawPanel.doLayout();
    }
    private void removeBall(){
        if(GameStateAndAction.isEndSignal()==false){
               GameStateAndAction.setEndSignal(true);
        }
        
        if(jTabbedPane1.getTabCount()==5){
            jButtonAddBall.setEnabled(true);
            Ball ball = new Ball();
            ball.setName("Ball5");
            balls.remove(ball);
            jLabelBall5VelX.setVisible(false);
            jLabelBall5VelY.setVisible(false);
            jTextFieldBall5VelX.setVisible(false);
            jTextFieldBall5VelY.setVisible(false);
           
          
        }else if (jTabbedPane1.getTabCount()==4){
            Ball ball = new Ball();
            ball.setName("Ball4");
            balls.remove(ball);
            jLabelBall4VelX.setVisible(false);
            jLabelBall4VelY.setVisible(false);
            jTextFieldBall4VelX.setVisible(false);
            jTextFieldBall4VelY.setVisible(false);
           
            
            
        }else if(jTabbedPane1.getTabCount()==3){
            jButtonRemoveBall.setEnabled(false);
            Ball ball = new Ball();
            ball.setName("Ball3");
            balls.remove(ball);
            jLabelBall3VelX.setVisible(false);
            jLabelBall3VelY.setVisible(false);
            jTextFieldBall3VelX.setVisible(false);
            jTextFieldBall3VelY.setVisible(false);
            
           
            
           
        }
         GameStateAndAction.setBalls(balls);
        jTabbedPane1.removeTabAt(jTabbedPane1.getTabCount()-1);
       
        
       if(GameStateAndAction.isEndSignal()==true && isPaused==false){
           GameStateAndAction.setEndSignal(false);
            t = new Thread(this);
            try {
                t.start();
            } catch (Exception ex) {
            }
           
        } 
       drawPanel.repaint();
       drawPanel.doLayout();
    }
    private void jButtonRemoveBallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveBallActionPerformed
       removeBall();
        
    }//GEN-LAST:event_jButtonRemoveBallActionPerformed

    private void drawPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMousePressed
       int x = evt.getX();
       int y = evt.getY();
       currentEllipse=getEllipse(x,y);
      /* if(currentEllipse==null){
          //not inside any elllipse
           if(jTabbedPane1.getTabCount()>=2 && jTabbedPane1.getTabCount()<5){
               addBall();
           }
            
       }*/
    }//GEN-LAST:event_drawPanelMousePressed

    private void drawPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMouseClicked
        

    }//GEN-LAST:event_drawPanelMouseClicked

    private void drawPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMouseMoved
        int x = evt.getX();
        int y = evt.getY();

        if (getEllipse(x,y)!=null) {

            setCursor(Cursor.getPredefinedCursor(Cursor.CROSSHAIR_CURSOR));

        } else {

            setCursor(Cursor.getDefaultCursor());

        }

    }//GEN-LAST:event_drawPanelMouseMoved

    private void drawPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMouseDragged
       
        int x = evt.getX();
        int y = evt.getY();

      if (currentEllipse!=null) {

        Graphics2D g = (Graphics2D) drawPanel.getGraphics();

            g.setXORMode(drawPanel.getBackground());
            g.draw(currentEllipse.getShape());

            currentEllipse.setX(x); 
            currentEllipse.setY(y);

            g.draw(currentEllipse.getShape());

            g.dispose();
            drawPanel.repaint();
            drawPanel.doLayout();

        }
    }//GEN-LAST:event_drawPanelMouseDragged
    
    private Ball getEllipse(int x, int y){
        //int ballIndex=-1;
        for (Ball ball : balls) {
           
           if(ball.getShape().contains(x,y)){
               
               currentEllipse=ball;
               return currentEllipse;
           }
            

        } 
        return null;
    }
    
    public void setJTextFieldBall1VelX(double text){
        String textForm =String.format("%.2f",Math.abs(text));
        jTextFieldBall1VelX.setText(textForm);
    }
     public void setJTextFieldBall1VelY(double text){
         String textForm =String.format("%.2f",Math.abs(text));
        jTextFieldBall1VelY.setText(textForm);
    }
    public void setJTextFieldBall2VelX(double text){
        String textForm =String.format("%.2f",Math.abs(text));
        jTextFieldBall2VelX.setText(textForm);
    }
    public void setJTextFieldBall2VelY(double text){
        String textForm =String.format("%.2f",Math.abs(text));
        jTextFieldBall2VelY.setText(textForm);
    }
    public void setJTextFieldBall3VelX(double text){
        String textForm =String.format("%.2f",Math.abs(text));
        jTextFieldBall3VelX.setText(textForm);
    }
    public void setJTextFieldBall3VelY(double text){
        String textForm =String.format("%.2f",Math.abs(text));
        jTextFieldBall3VelY.setText(textForm);
    }
    public void setJTextFieldBall4VelX(double text){
        String textForm =String.format("%.2f",Math.abs(text));
        jTextFieldBall4VelX.setText(textForm);
    }
    public void setJTextFieldBall4VelY(double text){
        String textForm =String.format("%.2f",Math.abs(text));
        jTextFieldBall4VelY.setText(textForm);
    }
    public void setJTextFieldBall5VelX(double text){
        String textForm =String.format("%.2f",Math.abs(text));
        jTextFieldBall5VelX.setText(textForm);
    }
    public void setJTextFieldBall5VelY(double text){
        String textForm =String.format("%.2f",Math.abs(text));
        jTextFieldBall5VelY.setText(textForm);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStartPause;
    private javax.swing.JPanel drawPanel;
    private javax.swing.JButton jButtonAddBall;
    private javax.swing.ButtonGroup jButtonGroupCollision;
    private javax.swing.JButton jButtonRemoveBall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBall1VelX;
    private javax.swing.JLabel jLabelBall1VelY;
    private javax.swing.JLabel jLabelBall2VelX;
    private javax.swing.JLabel jLabelBall2VelY;
    private javax.swing.JLabel jLabelBall3VelX;
    private javax.swing.JLabel jLabelBall3VelY;
    private javax.swing.JLabel jLabelBall4VelX;
    private javax.swing.JLabel jLabelBall4VelY;
    private javax.swing.JLabel jLabelBall5VelX;
    private javax.swing.JLabel jLabelBall5VelY;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelBallVelocity;
    private javax.swing.JRadioButton jRadioButtonElastic;
    private javax.swing.JRadioButton jRadioButtonInelastic;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldBall1VelX;
    private javax.swing.JTextField jTextFieldBall1VelY;
    private javax.swing.JTextField jTextFieldBall2VelX;
    private javax.swing.JTextField jTextFieldBall2VelY;
    private javax.swing.JTextField jTextFieldBall3VelX;
    private javax.swing.JTextField jTextFieldBall3VelY;
    private javax.swing.JTextField jTextFieldBall4VelX;
    private javax.swing.JTextField jTextFieldBall4VelY;
    private javax.swing.JTextField jTextFieldBall5VelX;
    private javax.swing.JTextField jTextFieldBall5VelY;
    private javax.swing.JSlider sliderAngle1;
    private javax.swing.JSlider sliderAngle2;
    private javax.swing.JSlider sliderAngle3;
    private javax.swing.JSlider sliderAngle4;
    private javax.swing.JSlider sliderAngle5;
    private javax.swing.JSlider sliderMass1;
    private javax.swing.JSlider sliderMass2;
    private javax.swing.JSlider sliderMass3;
    private javax.swing.JSlider sliderMass4;
    private javax.swing.JSlider sliderMass5;
    private javax.swing.JSlider sliderRadius1;
    private javax.swing.JSlider sliderRadius2;
    private javax.swing.JSlider sliderRadius3;
    private javax.swing.JSlider sliderRadius4;
    private javax.swing.JSlider sliderRadius5;
    private javax.swing.JTextField txtSpeed1;
    private javax.swing.JTextField txtSpeed2;
    private javax.swing.JTextField txtSpeed3;
    private javax.swing.JTextField txtSpeed4;
    private javax.swing.JTextField txtSpeed5;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        GameStateAndAction.runGame();
    }

   

    
    
}
